test_calibration:
  ros__parameters:
    channel: "SimpleChannelUDP"
    ff_device_ip_address: "192.168.100.53"
    ff_device_param_file: "/etc/Haption/Connector/desktop_6D_n65.param"
    local_ip_address: "192.168.100.50"