haptic_control:
  ros__parameters:
    channel: "SimpleChannelUDP"
    ff_device_ip_address: "192.168.100.53"
    ff_device_param_file: "/etc/Haption/Connector/desktop_6D_n65.param"
    local_ip_address: "192.168.100.50"
    force_max: 6.0 # Newton
    force_scale: 0.4
    smooth_factor: 0.55 # smoothing factor for the force feedback, acts as a low pass filter, 0 is no smoothing, 1 is no update

    # Control parameters
    haptic_control_rate: 1000.0 # Hz
    simulated_delay: 0.0 # round trip simulated delay in seconds (0.0 for no delay)
    tool_vis_radius: 0.005 # radius of the end effector sphere for visualization in Rviz

    # Virtual Fixture parameters to constrain the end effector over a mesh
    vf_parameters:
      mesh_type: "file" # knot, sphere, file, bunny
      # input_mesh_path: "/home/nardi/temp/vf/virtual_fixtures.obj" # path to the input mesh if mesh_type is file
      output_mesh_path: "/home/nardi/temp/vf_output/virtual_fixtures_vis.obj" # path to save the output mesh for Rviz visualization
      # skin_mesh_path: "/home/nardi/temp/vf/skin_mesh.obj" # path to the skin mesh if mesh_type is file
      tool_radius: 0.002 # radius of the end effector sphere for the virtual fixture plane search

      lookup_area: 0.004 # area around the end effector to look for the closest point on the mesh
      plane_size: 0.002 # plane size used to visualize active constraints in rviz

      # Conic Control Barrier Function parameters to constraint the robot orientation inside a cone
      use_ccbf: true
      ccbf_params:
        use_initial_conf_as_q_ref: true # if true, the initial end effector orientation is used as the reference orientation
        ccbf_q_ref: [0.21006, 0.97703, 0.018034, 0.031066] # quaternion in the form [x, y, z, w] for the reference orientation of the end effector, considered only if use_initial_conf_as_q_ref is false
        ccbf_thetas: [0.4, 0.4, 0.4] # angle in radians for each axis of R_ref (which is q_ref as a rotation matrix)
        # ccbf_thetas: [0.3 , 0.3, 0.3]

keyboard_control:
  ros__parameters:
    vf_parameters:
      mesh_type: "bunny" # knot, sphere, file, bunny
      output_mesh_path: "/home/nardi/virtual_fixture_vis.obj" # path to save the output mesh for Rviz visualization
      # input_mesh_path: "/home/nardi/SKEL_WS/ros2_ws/final_vf.obj" # path to the input mesh if mesh_type is file
      # skin_mesh_path: "/home/nardi/SKEL_WS/ros2_ws/skin_mesh.obj" # path to the skin mesh if mesh_type is file
      tool_radius: 0.001 # radius of the end effector sphere
      tool_visualization_radius: 0.01 # radius of the end effector sphere for visualization in Rviz

      lookup_area: 0.005 # area around the end effector to look for the closest point on the mesh
      plane_size: 0.002 # plane size used to visualize active constraints in rviz
