haptic_control:
  ros__parameters:
    tool_link_name: "lbr_link_ee"
    base_link_name: "lbr_link_0"
    ft_link_name: "lbr_link_ee"
    ft_sensor_rate: 1000.0
    target_frame_topic_name: "/lbr/target_framee"
    base_frame_rotation: [0.0, 0.0, 1.0, 0.0] # quaternion in the form [x, y, z, w], it is used to align the robot base link with the haptic interface base link
    ft_feedback_topic_name: "/lbr/force_torque_broadcaster/wrench"