haptic_control:
  ros__parameters:
    channel: "SimpleChannelUDP"
    ff_device_ip_address: "192.168.100.53"
    ff_device_param_file: "/etc/Haption/Connector/desktop_6D_n65.param"
    local_ip_address: "192.168.100.50"
    max_force: 6.0
    # robot position safety limits
    min_x: -1.0
    max_x: 1.0
    min_y: -1.0
    max_y: 1.0
    min_z: -1.0
    max_z: 1.0