
haptic_control:
  ros__parameters:
    # vf params
    mesh_type: "file" # knot, sphere, file, bunny 
    input_mesh_path: "/home/nardi/SKEL_WS/ros2_ws/final_vf.obj"
    skin_mesh_path: "/home/nardi/SKEL_WS/ros2_ws/skin_mesh.obj"
    output_mesh_path : "/home/nardi/SKEL_WS/ros2_ws/final_vf2.obj"
    radius: 0.001
    lookup_area: 0.01 # should be at least 2*radius
    plane_size: 0.01 # plane size used to visualize active constraints in rviz

    channel: "SimpleChannelUDP"
    ff_device_ip_address: "192.168.100.53"
    ff_device_param_file: "/etc/Haption/Connector/desktop_6D_n65.param"
    local_ip_address: "192.168.100.50"
    # vf params

    enable_safety_sphere: false
    safety_sphere_radius: 0.48
    use_limits: false
    min_x:  -100.0
    max_x:  100.0
    min_y:  -100.0
    max_y:  100.0
    min_z:  -100.0
    max_z:  100.0
    # min_x_:  0.33
    # max_x_:  0.48
    # min_y_: -0.03
    # max_y_:  0.18
    # min_z_:  -0.10
    # max_z_:  0.13

    tool_link_name: "probe"
    base_link_name: "base_link"
    ft_link_name: "ft_sensor0_wrench"
    force_scale : 0.3
    # safety box that can be activated (centered in the current ee position)
    enable_safety_box: false 
    safety_box_length: 0.2
    safety_box_width: 0.2
    safety_box_height: 0.2

vf_control:
  ros__parameters:
    mesh_type: "file" # knot, sphere, file, bunny 
    input_mesh_path: "/home/nardi/SKEL_WS/ros2_ws/final_vf.obj"
    skin_mesh_path: "/home/nardi/SKEL_WS/ros2_ws/skin_mesh.obj"
    output_mesh_path : "/home/nardi/SKEL_WS/ros2_ws/final_vf2.obj"
    radius: 0.001
    lookup_area: 0.01 # should be at least 2*radius
    plane_size: 0.01 # plane size used to visualize active constraints in rviz