name: Humble CI

on:
  push:
    branches:
      - main
          
jobs:
  humble_source:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package-name: 
          - test_calibration
          - test_admittance
          - test_impedance
          - haptic_control
    steps:
      # Step 1: Set up ROS Humble
      - name: Setup ROS Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # Step 2: Install additional dependencies
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libpciaccess-dev libomp-dev

      # Step 3: Clone and build Open3D with caching
      - name: Cache Open3D Build
        uses: actions/cache@v3
        with:
          path: Open3D/build
          key: ${{ runner.os }}-open3d-${{ hashFiles('Open3D/**') }}

      - name: Clone and Build Open3D
        run: |
          git clone https://github.com/isl-org/Open3D || true
          cd Open3D
          source util/install_deps_ubuntu.sh || exit 1
          mkdir -p build && cd build
          cmake .. || exit 1
          make -j$(nproc) || exit 1
          sudo make install || exit 1

      # Step 4: Build and process each ROS package
      - name: Build and Process ROS Package
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: ${{ matrix.package-name }}
          target-ros2-distro: humble
          skip-tests: true