name: Humble CI

on:
  push:
    branches:
      - main
          
jobs:
  humble_source:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: sudo apt-get install -y libpciaccess-dev libomp-dev
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
